version: "3.8"

services:

  api-gateway:
    image: silentghost1/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - quote-service
      - user-service

  quote-service:
    image: silentghost1/quote-service:latest
    container_name: quote-service
    restart: unless-stopped
    ports:
      - "8081:8081"

  user-service:
    image: silentghost1/user-service:latest
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8082:8082"
